apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
        - name: qas-taging
          image: nginx:alphine
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-1-config
            - secretRef:
                name: app-1-secret
          resources: 
            limits:
              memory: "120Mi"
              cpu: "200m" #
            requests: 
              memory: "64Mi"
              cpu: "100m"
